pipeline {
    agent any
    stages {
        stage('Spellcheck by Linter'){
            steps{
                echo 'Spellcheck by Linter'                
                sh '''	
                    pylint  --recursive=y app.py 
                '''
            } 
        }
    }
}
