pipeline {
    agent any    
    stages{
        stage('Pre-Build'){
            steps{
                echo 'Checking pre-requisites'                
                sh'''
                    export PATH=$PATH:~/.local/bin
                    sudo apt-get update
                    sudo apt-get install -y wget curl python3 python3-pip python3-pep8 python3-flask pipenv pylint codespell
                    pip3 install -r requirements.txt
                '''
            }
        }

        stage('Trigger Pipelines') {
            steps {
                script {
                    def token = 't1'
                    def jenkinsUrl = 'http://localhost'
                    def jobNames = ['spellcheck', 'codespell', 'tests', 'build']

                    jobNames.each { jobName ->
                        sh """
                        curl -X POST ${jenkinsUrl}/job/${jobName}/build \
                        --user admin:${token}
                        """
                    }
                }
            }
        }
    }
}
